plugins {
    id "maven-publish"
    id "dev.architectury.loom" version "1.13-SNAPSHOT" apply false
    id "me.modmuss50.mod-publish-plugin" version "1.1.0"
    id "dev.ithundxr.silk" version "1.0.1"
}

allprojects {
    group = "org.antarcticgardens.cna"
    version = "${rootProject.modVersion}+${project.name}-mc${rootProject.minecraftVersion}"
}

subprojects {
    apply plugin: "java"
    apply plugin: "maven-publish"
    apply plugin: "dev.architectury.loom"
    apply plugin: "me.modmuss50.mod-publish-plugin"
    apply plugin: "dev.ithundxr.silk"

    base {
        archivesName = "create-new-age"
    }

    repositories {
        mavenLocal()
        mavenCentral()

        maven { url "https://maven.neoforged.net/releases/" }
        maven { url = "https://cursemaven.com" } // CurseForge maven
        maven { url = "https://api.modrinth.com/maven" } // Modrinth maven
        
        maven { url = "https://maven.parchmentmc.org" } // Parchment mappings
        maven { url = "https://maven.tterrag.com/" } // Forge Registrate

        maven { url = "https://maven.createmod.net" } // Create Forge, Ponder, Flywheel

        maven { url = "https://mvn.devos.one/snapshots/" } // Create Fabric, Fabric Registrate

        maven { url = "https://maven.idiotss.com/releases/" } // ESL

        maven { url = "https://maven.blamejared.com/" } // JEI
        
        // Create dependencies
        maven { url = "https://maven.jamieswhiteshirt.com/libs-release" } // Reach Entity Attributes
        
        maven { url = "https://jitpack.io/" } // Mixin Extras

        maven { url "https://maven.squiddev.cc" // Computer Craft Tweaked
            content {
                includeGroup("cc.tweaked")
            }
        }

        // Sable
        exclusiveContent {
            forRepository {
                maven {
                    url = "https://maven.ryanhcode.dev/releases"
                    name = "RyanHCode Maven"
                }
            }
            filter {
                includeGroup("dev.ryanhcode.sable")
                includeGroup("dev.ryanhcode.sable-companion")
            }
        }
    }
    
    dependencies {
        minecraft "com.mojang:minecraft:${rootProject.minecraftVersion}"
        
        mappings(loom.layered {
            it.officialMojangMappings()
            it.parchment("org.parchmentmc.data:parchment-${rootProject.minecraftVersion}:${rootProject.parchmentVersion}@zip")
        })
        
        annotationProcessor("systems.manifold:manifold-preprocessor:2024.1.29")

        modImplementation(include("org.antarcticgardens.esl:esl-${project.name}-${rootProject.minecraftVersion}:${rootProject.eslVersion}+${project.name}-mc${rootProject.minecraftVersion}"))
        
        modCompileOnlyApi("mezz.jei:jei-${rootProject.minecraftVersion}-common-api:${rootProject.jeiVersion}")

        if (project.name != "common") {
            if (recipeViewer == "jei") {
                modRuntimeOnly("mezz.jei:jei-${rootProject.minecraftVersion}-${project.name}:${rootProject.jeiVersion}")
            }
        }
    }

    loom {
        accessWidenerPath = project(":common").file("src/main/resources/create_new_age-common.accesswidener")
    }
    
    sourceSets {
        main {
            resources {
                srcDirs += [
                        'src/generated/resources'
                ]
            }
        }
    }
    
    jar {
        archiveClassifier.set("dev")
    }
    
    java {
        withSourcesJar()
    }

    publishing {
        publications {
            maven(MavenPublication) {
                artifactId = base.archivesName.get() + "-${project.name}-${rootProject.minecraftVersion}"
                if (!System.getenv("RELEASE").asBoolean())
                    version = "${rootProject.modVersion}-build.${System.getenv("GIT_SHA")}+${project.name}-mc${rootProject.minecraftVersion}"
                from components.java
            }
        }
        var mavenURL = System.getenv("RELEASE").asBoolean() ? "releases" : "snapshots"
        repositories {
            maven {
                url = "https://maven.idiotss.com/" + mavenURL
                credentials{
                    username = System.getenv("MAVEN_NAME")
                    password = System.getenv("MAVEN_SECRET")
                }
            }
        }

    }

    tasks.withType(JavaCompile) {
        options.compilerArgs += ['-Xplugin:Manifold']
        options.encoding = "UTF-8"
        options.release = 21
    }
}
