modLoader="javafml"
loaderVersion="*"

license="BSD-3-Clause"
issueTrackerURL="https://gitlab.com/antarcticgardens/create-new-age"
showAsResourcePack=false

[[mods]]
modId="create_new_age"
version="${version}"
displayName="Create: New Age"
logoFile="icon.png"
authors="Antarctic Gardens"
description="An addon for the Create mod that adds integration with electricity"
displayTest="MATCH_VERSION"
displayURL="https://antarcticgardens.org/"
[[mixins]]
config="create_new_age-neoforge.mixins.json"
[[mixins]]
config="create_new_age-common.mixins.json"

[[dependencies.create_new_age]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforgeVersion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraftVersion}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="esl"
    type="required"
    versionRange="[${eslVersion}]"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="create"
    type="required"
    versionRange="[${createVersion},6.1.0)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="computercraft"
    type="optional"
    versionRange="[${cctVersion},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_new_age]]
    modId="sablecompanion"
    type="optional"
    versionRange="[${sableCompanionVersion},)"
    ordering="AFTER"
    side="BOTH"