dependencies {
    compileOnly(project(":common"))
    neoForge("net.neoforged:neoforge:${project.neoforgeVersion}")

    modImplementation("com.simibubi.create:create-${rootProject.minecraftVersion}:${rootProject.createVersion}:slim") { transitive = false }
    modImplementation("net.createmod.ponder:ponder-neoforge:${ponderVersion}+mc${minecraftVersion}")
    modCompileOnly("dev.engine-room.flywheel:flywheel-neoforge-api-${minecraftVersion}:${flywheelVersion}")
    modRuntimeOnly("dev.engine-room.flywheel:flywheel-neoforge-${minecraftVersion}:${flywheelVersion}")
    modApi("com.tterrag.registrate:Registrate:${rootProject.registrateVersion}")

    if (enableCraftsAndAdditions.toBoolean()) {
        modRuntimeOnly("maven.modrinth:createaddition:neoforge-${minecraftVersion}-${craftsAndAdditionsVersion}")
    }
    if (enableAE2.toBoolean()) {
        modRuntimeOnly("org.appliedenergistics:appliedenergistics2:${appliedEnergistics2Version}")
    }

    compileOnly("io.github.llamalad7:mixinextras-common:0.5.0")
    annotationProcessor(implementation(include("io.github.llamalad7:mixinextras-neoforge:0.5.0")))

    // Computer Craft stuffs
    modCompileOnly("cc.tweaked:cc-tweaked-${rootProject.minecraftVersion}-forge-api:${rootProject.cctVersion}")
    if (enableCCT.toBoolean()) {
        modRuntimeOnly("cc.tweaked:cc-tweaked-${rootProject.minecraftVersion}-forge:${rootProject.cctVersion}")
        // Required to be able to run CC:Tweaked
        forgeRuntimeLibrary("cc.tweaked:cobalt:0.9.7")
    }

    include(api("dev.ryanhcode.sable-companion:sable-companion-common-${minecraftVersion}:[${project.sableCompanionVersion},)"))
}

processResources {
    from(project(":common").sourceSets.main.resources)

    var replaceProperties = [
            "version"              : version.replaceAll("\\+.*-mc", "\\+mc"),
            "minecraftVersion"     : minecraftVersion,
            "neoforgeVersion"      : neoforgeVersion,
            "eslVersion"           : eslVersion,
            "createVersion"        : createVersionShort,
            "cctVersion"           : cctVersion,
            "sableCompanionVersion": sableCompanionVersion,
            "objLoader"            : objLoader,
    ]

    inputs.properties replaceProperties

    filesMatching(["META-INF/neoforge.mods.toml", "assets/**/*.json"]) {
        expand replaceProperties
    }
}

compileJava {
    source(project(":common").sourceSets.main.allSource)
}

var modId = rootProject.modId


loom {
    runs {
        datagen {
            data()
            programArgs("--all", "--mod", "${modId}")
            programArgs("--output", file("src/generated/resources").absolutePath)
            programArgs("--existing", file("../common/src/main/resources").absolutePath)
        }
    }
}

// https://modmuss50.github.io/mod-publish-plugin/
publishMods {
    file = remapJar.archiveFile
    changelog = rootProject.silk.changelog
    type = STABLE
    version = "$modVersion+mc$minecraftVersion"
    displayName = "$modVersion for Neoforge $minecraftVersion"
    modLoaders.add("neoforge")

    curseforge {
        accessToken = providers.environmentVariable("CURSEFORGE_TOKEN")
        projectId = "905861"
        clientRequired = true
        serverRequired = true
        requires("create")
        minecraftVersions.add(minecraftVersion)
    }

    modrinth {
        accessToken = providers.environmentVariable("MODRINTH_TOKEN")
        projectId = "FTeXqI9v"
        requires { // Requires Create
            id = "LNytGWDc"
        }
        minecraftVersions.add(minecraftVersion)
    }
}
